# Generated by Django 5.0.3 on 2024-04-17 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_first_person_room_second_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 6, 11, 20, 904654, tzinfo=datetime.timezone.utc)),
        ),
    ]
