# Generated by Django 5.0.3 on 2024-04-18 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 1, 58, 51, 508250, tzinfo=datetime.timezone.utc)),
        ),
    ]
