# Generated by Django 5.0.3 on 2024-04-18 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_room_room_name_room_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 2, 22, 27, 954299, tzinfo=datetime.timezone.utc)),
        ),
    ]
